storage:
  type: postgres
  path: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}?sslmode=disable"

alerting:
  telegram:
    token: ${TELEGRAM_BOT_TOKEN}
    id: ${TELEGRAM_USER_ID}

#security:
#  basic:
#    username: "john.doe"
#    password-bcrypt-base64: "JDJhJDEwJHRiMnRFakxWazZLdXBzRERQazB1TE8vckRLY05Yb1hSdnoxWU0yQ1FaYXZRSW1McmladDYu"

endpoints:
  - name: back-end
    group: core
    url: "https://example.org/"
    interval: 5s
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: telegram
        send-on-resolved: true

  - name: monitoring
    group: internal
    url: "https://example.org/"
    interval: 10s
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: telegram
        send-on-resolved: true

  - name: example-dns-query
    url: "8.8.8.8" # Address of the DNS server to use
    interval: 1m
    dns:
      query-name: "example.com"
      query-type: "A"
    conditions:
      - "[BODY] == 93.184.215.14"
      - "[DNS_RCODE] == NOERROR"

  - name: icmp-ping
    url: "icmp://example.org"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"